version: "3.8"

services:
  tailscale:
    image: ghcr.io/lpasselin/tailscale-docker:latest
    environment:
      TAILSCALE_AUTH_KEY: tskey-auth-kCuaX26CNTRL-xCnnx2f8rBVQthUddukd9VgnxMYfwwnE
      TAILSCALE_HOSTNAME: cmdargnodename
      TAILSCALE_STATE_ARG: "/var/lib/tailscale_state/tailscale.state"
    volumes:
      - /var/lib/tailscale_state/
    restart: unless-stopped
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      MEMORY: "cmdargram"
      TYPE: "CUSTOM"
      FORCE_REDOWNLOAD: "true"
      CUSTOM_SERVER: "multipaper.jar"
      JVM_OPTS: '-DbungeecordName=cmdargnodename -Dproperties.view-distance=cmdargvd -Dpaper.settings.perform-username-validation=false -Dpaper.settings.proxy-protocol=true -DmultipaperMasterAddress=100.67.95.52:35353'
    volumes:
      - type: bind
        source: ./data/wse-serversetup
        target: /data
    stdin_open: true
    tty: true
    network_mode: "service:tailscale"
    restart: unless-stopped
volumes:
  data: {}